- name: Jenkins
  hosts: jenkins
  tasks:
    - name: Install python-software-properties
      sudo: false
      #local_action: "{{ ansible_pkg_mgr }} pkg=python-software-properties state=installed"
      action: ping

    - name: Install python-pycurl
      sudo: false
      local_action: "{{ ansible_pkg_mgr }} pkg=python-pycurl state=installed"
      #action: ping
    # Add Jenkins repository key
    - name: Add jenkins apt-key
      sudo: false
     # local_action: apt_key data="{{ lookup('file', 'jenkins-ci.org.key') }}" state=present
      action: ping
     
      #roles:
      #  - ansible-jenkins
   
  
